### ISSUE TITLE
banned pages

### ISSUE THREAD

**Issue by gaziway** [gigablast/open-source-search-engine#102]
Hello, 

not an issue...
I would like to know how can one delete pages which are reported as:
"omitted because they were considered duplicates, banned, errors 
or from the same site as other results.".

If there is no direct way of doing so, how can we get the list of same, so we could delete them by using indirect approaches.

thanks

**Comment by gigablast** [comment]
you can use the 'inject url' tool to inject those urls into the index and then check the 'delete' checkbox so they are deleted instead of re-injected.
