### ISSUE TITLE
Defect in "atob" function ?

### ISSUE THREAD

**Issue by AppChecker** [gigablast/open-source-search-engine#106]
Hi!

In function atob (fctypes.cpp, line 1044)

1) [suspicious conditional:](https://github.com/gigablast/open-source-search-engine/blob/8891100c2a91526c92510ac640978b17415ab0a6//fctypes.cpp#L1052)

`s[0] == 'y' || s[0] == 'y'`

may be it should be:
`s[0] == 'y' || s[0] == 'Y'`
?

2)
 `if ( s[0] == 't' || s[1] == 'T' )`

may be it should be:
`s[0] == 't' || s[0] == 'T'`

These possible defects found by AppChecker.

**Comment by gigablast** [comment]
i don't think it really matters, but this is now fixed.
