### ISSUE TITLE
NO PERMISSION after setting password

### ISSUE THREAD

**Issue by turbo** [gigablast/open-source-search-engine#110]
After setting a "master password" (and no IP), I immediately get "NO PERMISSION" for every page I try to access.

How can I access the admin console using the password?

**Comment by minxomat** [comment]
In the online demo, the "Admin" link leads to a login page. When I try to access that page (`admin/settings?c=main` ) on my instance, I get the same permission error.

**Comment by pstewart726** [comment]
I've run across that situation before as well .... check on the server in the directory where you are running GB for gb.conf file and check in that file for the same settings.  Suggest removing the password temporarily and restart to see if that helps....

The last time I ran across this, I had the same thing happen ... I edited gb.conf file and restarted GB ... then went back and put my password back in via the web interface and everything was fine again.

**Comment by minxomat** [comment]
Did you compile it yourself or use the binary? I've only tested the 2014 deb package so far, which spills it's contents into /var/. Adjusting the conf in that made no difference, furthermore, ` gb stop`  doesn't do anything (launched it with `gb -d`).

The GH source code does compile (after fixing an issue in Mem.cpp), but it simply doesn't do anything. I haven't spent much time with it, just asking if you've used this code from source.

**Comment by pstewart726** [comment]
I didn't have great success with package version - I always compile :)  One thing I do recall is that gb -d doesn't seem to work ... it used to quite well .. I use "gb start" and that works as it kicks in the process via shell script

**Comment by bubul01** [comment]
Yes, i've the same problem and i don't know what to do, now i've not set password so i can access to admin pages !
