### ISSUE TITLE
Error no gb.conf file

### ISSUE THREAD

**Issue by K3r0sen** [gigablast/open-source-search-engine#13]
Did all compile procedures from http://www.gigablast.com/admin.html#quickstart

After run ./gb 0 got this error:

1383184149750 000 WARN  disk    error open(/home/webdev/gb/gb.conf) : No such file or directory
1383184149750 000 WARN  disk    open: No such file or directory
1383184149750 000 WARN  conf    Could not open /home/webdev/gb/gb.conf: No such file or directory.

But the file exist there

**Comment by lisawebcoder** [comment]
hello i am having the same issue
after i complete all steps 
when i run ./gb or gb or ./gb -d i get file not found

how exactly do you solve this?
regards

Lisa

**Comment by lisawebcoder** [comment]
hello should i change directory to as an example
/home/Lisa/webdev/gb/gb.conf?
and then run gb start from there?
the steps make no mention that we need to change dorectory after the make is finsihder

Lisa

**Comment by lisawebcoder** [comment]
is the gb folder created by the make command?
i 1st had to fix Mem.cpp  there was an error
then now i am running make again with no error in Mem.cpp
but so far i dont see this gb folder and this gb.conf file
are there any depnadicies still missing?
i dont beleive so since i did wget archive master zip archive file so it should be the classic files

Lisa

**Comment by lisawebcoder** [comment]
i am in /root/home/lisa/gigablast/open-source-search-engine folder

make just complted and i still get an error
usr/bin/ld final link failed failed non respresanble section on output
collect2 error ld retuened 1 exit staus 
Makefile 196 recipe for target 'gb' failed
errror 1

so does this mean the gb folder agin was not created?

i am on ubuntu 18.04
do i have to use ubuntu 14.04?

hello can anyine help me out?

Lisa

**Comment by lisawebcoder** [comment]
hello there are some erros liek its says in usr/bin/ld bit i dont find this fodler
and there are eroors that stop the make command from making the recipe to create the gb file

how do i get around this the errors are not clear to fic

Lisa

**Comment by lisawebcoder** [comment]
g++ -D_REENTRANT_ -D_CHECK_FORMAT_STRING_ -I. -g -Wall -pipe -fno-stack-protector -Wno-write-strings -Wstrict-aliasing=0 -Wno-uninitialized -DPTHREADS -Wno-unused-but-set-variable  -o gb main.o UdpSlot.o Rebalance.o Msg13.o Mime.o PageGet.o PageHosts.o PageParser.o PageInject.o PagePerf.o PageReindex.o PageResults.o PageAddUrl.o PageRoot.o PageSockets.o PageStats.o PageTitledb.o PageAddColl.o hash.o Domains.o Collectiondb.o linkspam.o ip.o sort.o fctypes.o XmlNode.o XmlDoc.o Xml.o Words.o Url.o UdpServer.o Threads.o Titledb.o HashTable.o TcpServer.o Summary.o Spider.o Catdb.o RdbTree.o RdbScan.o RdbMerge.o RdbMap.o RdbMem.o RdbBuckets.o RdbList.o RdbDump.o RdbCache.o Rdb.o RdbBase.o Query.o Phrases.o Multicast.o Msg9b.o Msg8b.o Msg5.o Msg39.o Msg3.o Msg22.o Msg20.o Msg2.o Msg1.o Msg0.o Mem.o Matches.o Loop.o Log.o Lang.o Indexdb.o Posdb.o Clusterdb.o IndexList.o Revdb.o HttpServer.o HttpRequest.o HttpMime.o Hostdb.o Highlight.o File.o Errno.o Entities.o Dns.o Dir.o Conf.o Bits.o Stats.o BigFile.o Msg17.o Speller.o PingServer.o StopWords.o TopTree.o Parms.o Pages.o Unicode.o iana_charset.o Iso8859.o SearchInput.o Categories.o Msg2a.o PageCatdb.o PageDirectory.o SafeBuf.o Datedb.o UCNormalizer.o UCPropTable.o UnicodeProperties.o Pops.o Title.o Pos.o LangList.o Profiler.o AutoBan.o Msg3a.o HashTableT.o HashTableX.o PageLogView.o Msg1f.o Blaster.o MsgC.o PageSpam.o Proxy.o PageThreads.o Linkdb.o matches2.o LanguageIdentifier.o Language.o Repair.o Process.o Abbreviations.o RequestTable.o TuringTest.o Msg51.o geo_ip_table.o Msg40.o Msg4.o SpiderProxy.o LanguagePages.o Statsdb.o PageStatsdb.o PostQueryRerank.o Msge0.o Msge1.o CountryCode.o DailyMerge.o CatRec.o Tagdb.o Users.o Images.o Wiki.o Wiktionary.o Scraper.o Dates.o Sections.o SiteGetter.o Syncdb.o qa.o Placedb.o Address.o Test.o GeoIP.o GeoIPCity.o Synonyms.o Cachedb.o Monitordb.o dlstubs.o PageCrawlBot.o Json.o PageBasic.o Punycode.o Version.o -lm -lpthread -lssl -lcrypto ./libiconv64.a ./libz64.a
/usr/bin/ld: ./libiconv64.a(iconv.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libiconv64.a(localcharset.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libz64.a(deflate.o): relocation R_X86_64_32S against hidden symbol `zcalloc' can not be used when making a PIE object
/usr/bin/ld: ./libz64.a(inflate.o): relocation R_X86_64_32S against hidden symbol `zcalloc' can not be used when making a PIE object
/usr/bin/ld: ./libz64.a(inftrees.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libz64.a(trees.o): relocation R_X86_64_32S against `.data' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libz64.a(zutil.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libz64.a(crc32.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./libz64.a(inffast.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
TcpServer.o: In function `TcpServer::reset()':
/home/robert/Desktop/gigablast/open-source-search-engine-master/TcpServer.cpp:61: undefined reference to `ERR_free_strings'
TcpServer.o: In function `TcpServer::init(void (*)(TcpSocket*), int (*)(char*, int, TcpSocket*), int (*)(TcpSocket*), short, int*, bool)':
/home/robert/Desktop/gigablast/open-source-search-engine-master/TcpServer.cpp:206: undefined reference to `SSL_library_init'
/home/robert/Desktop/gigablast/open-source-search-engine-master/TcpServer.cpp:207: undefined reference to `SSL_load_error_strings'
/home/robert/Desktop/gigablast/open-source-search-engine-master/TcpServer.cpp:211: undefined reference to `SSLv23_method'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:196: recipe for target 'gb' failed
make: *** [gb] Error 1

**Comment by lisawebcoder** [comment]
hello i dont understanbd anymore what is going on
i was able to install with ubuntu software on 32 bit deb package 1386 and now it says there is gb software package installed but its a build tool for the Go programming language

and nothing works if i put gb 
it justs gives me the help with the command to buitl go projects
what is this all about
i dont undertand ubuntu software clearly said this is a gb sercgh engine 

and it says gb is installed 
it wont install at the comd line i still get endless errors

Lisa

**Comment by lisawebcoder** [comment]
hello i dont have the gb.conf file 
all i have is the gb icon which i dont know what that is
do you have the gb.conf file
can you provide it ?

Lisa

**Comment by lisawebcoder** [comment]
this seems like the deb package is corrupted?
why did it install the go package?
thats not the search engine
i am so confuesd now

ubunut says its installed and its the search engine
hello anyone here?
Lisa
