### ISSUE TITLE
Cleaner Theme

### ISSUE THREAD

**Issue by maverick74** [gigablast/open-source-search-engine#147]
Would be good to have a cleaner theme! 

Something more in line with Google or DuckDuckGo (or searx.me's simple theme)

**Comment by didlie** [comment]
forget cleaner theme... why not just get the JSON output and do whatever you want with it. Wheres the documentation?

**Comment by maverick74** [comment]
Nah...
too much geeky!

With all the buzz about google not being fair about the results it returns, the world needs an open-source search engine!

GigaBlast, since it has it's own crawler, could be the one - and a cleaner theme could help A LOT!

Then again we could all just sit and wish another search engine shows up...

**Comment by didlie** [comment]
the didlie.com project is all about "business real estate in the information age." Check out the project on linkedIn

**Comment by maverick74** [comment]
but... is there anything related to search engine?

**Comment by maverick74** [comment]
@gigablast any chance on this?

**Comment by maverick74** [comment]
private.sh has a nice theme!!!

Now if only they would add image search and gigablast credit on that page..........

**Comment by maverick74** [comment]
@gigablast Loved the new layout!!!

i'm going to close this as the reason for opening it no longer exists. Thanks
