### ISSUE TITLE
Centos 8 build fails

### ISSUE THREAD

**Issue by cognitivepedr0** [gigablast/open-source-search-engine#164]
Hi all,

I am failing to build this software, I get this error:

Mem.cpp:233:8: error: declaration of ‘void* operator new(size_t) throw (std::bad_alloc)’ has a different exception specifier
 void * operator new (size_t size) throw (std::bad_alloc) {

I am not new to C/C++ development but I am puzzled, it seems that the compiler version I am using is incorrect or the source code is broken - the former being more likely I reckon

**Comment by onlyjob** [comment]
Same FTBFS on Debian with _gcc_ 10.2.1:

```
Mem.cpp:233:8: error: declaration of ‘void* operator new(size_t) throw (std::bad_alloc)’ has a different exception specifier 
  233 | void * operator new (size_t size) throw (std::bad_alloc) { 
      |        ^~~~~~~~ 
```

The following page might provide some insights: https://stackoverflow.com/questions/39188919/different-exception-specifier-with-g-6-2

Compiling with `-std=c++98` progressed further but stopped on another problem:

```
Threads.cpp:3357:3: error: ‘pthread_join’ was not declared in this scope; did you mean ‘pthread_kill’? 
 3357 |   pthread_join ( e->m_joinTid , NULL ); 
      |   ^~~~~~~~~~~~ 
      |   pthread_kill 
```

Un-commenting `#define PTHREADS` in `Threads.cpp` (https://github.com/gigablast/open-source-search-engine/blob/master/Threads.cpp#L20) helped which suggests defect in the `Makefile`.

**Comment by lisawebcoder** [comment]
this should be the fix



 Are you using C++11 or later?

The original operator new() declarations in C++98

throwing:   
void* operator new (std::size_t size) throw (std::bad_alloc);

nothrow:
void* operator new (std::size_t size, const std::nothrow_t& nothrow_value) throw();

placement:
void* operator new (std::size_t size, void* ptr) throw();

Have been changed in C++11 to use noexcept keyword:

throwing:   
void* operator new (std::size_t size);

nothrow:    
void* operator new (std::size_t size, const std::nothrow_t& nothrow_value) noexcept;

placement:  
void* operator new (std::size_t size, void* ptr) noexcept;
