### ISSUE TITLE
Incorrect comparison with PCLIX

### ISSUE THREAD

**Issue by GrosQuildu** [gigablast/open-source-search-engine#201]
https://github.com/gigablast/open-source-search-engine/blob/6474e32956384b042db14ee9177137483e7ea965/Address.cpp#L14813

"PCLIX" length is 5, not 4.

**Comment by tcreek** [comment]
You can try putting in a pull request, but we think this project has been abandoned

**Comment by GrosQuildu** [comment]
Uh, haven't looked at last update time. Should be archived I guess... Closing therefore.

**Comment by tcreek** [comment]
There was a pull request from eight months ago which was honored. 

Maybe you should do it, and maybe one of the persons will approve it.

We think the project has been abandoned is because the devs have done no work on it for over two years, and even the Gigablast site has been down for weeks.
