### ISSUE TITLE
Compile in Cygwin

### ISSUE THREAD

**Issue by Yeeler** [gigablast/open-source-search-engine#33]
I have a question that if it can be compiled in Cygwin. I noticed that you left some comments about it at the Makefile, but still not sure how to do it. Could you please give me some advices? Thank you.

**Comment by lisawebcoder** [comment]
hello does anyone have the complete steps to run on cygwin?
i tried many times on ubuntu but make nver creates the gb exctable file or there is somethin i dont know amount
also i dont know how to run your api 
i run wiki api easliy

Lisa
