### ISSUE TITLE
Indexes css files

### ISSUE THREAD

**Issue by b-rasmusson** [gigablast/open-source-search-engine#38]
This is an example dump from one of my spiderdbs:

offset=2995650 k=0x06bbcb5bd359a2a01fcffb999d515001 REQ uh48=232381933952975 recsize=142 parentDocId=265429100712 firstip=91.203.187.6 hostHash32=0xb6cc6794 domHash32=0x306d52b9 siteHash32=0xb6cc6794 siteNumInlinks=0 addedTime=Mar  3 11:33:58 2015 UTC(1425382438) parentFirstIp=91.203.187.14 parentHostHash32=0xa6f718a4 parentDomHash32=0xdf624a2 parentSiteHash32=0xa6f718a4 hopCount=1 ufn=-1 priority=-1 ISNEWOUTLINK PARENTHASADDRESS shardnum=88 url=http://static.v5.skyrock.net/css/common.css?en94Zsw requestage=4753434s hadReply=0 errcount=1 errcode=32825(Doc is a dup)

offset=18886075 k=0x2b1c5e408fea089ae039fbc9321c6401 REQ uh48=158235329486905 recsize=132 parentDocId=265828240946 firstip=64.94.28.43 hostHash32=0x8a8058ba domHash32=0xd9e1fd38 siteHash32=0x8a8058ba siteNumInlinks=0 addedTime=Apr 27 10:50:49 2015 UTC(1430131849) parentFirstIp=64.94.28.43 parentHostHash32=0x8a8058ba parentDomHash32=0xd9e1fd38 parentSiteHash32=0x8a8058ba hopCount=1 ufn=-1 priority=-1 SAMEDOM SAMEHOST SAMESITE WASPARENTINDEXED HASCONTACTINFO shardnum=88 url=http://sircloud.sirweb.org/css/styles.css requestage=5021s hadReply=0 errcount=0 errcode=0

As you can see, GB indexes CSS files, both if they have URL parameters or not. 

I don't think it should?

**Comment by gigablast** [comment]
there's a fix now for this in the testing branch.
will be in the main branch in due time.

On 04/27/2015 04:59 AM, b-rasmusson wrote:
>
> This is an example dump from one of my spiderdbs:
>
> offset=2995650 k=0x06bbcb5bd359a2a01fcffb999d515001 REQ 
> uh48=232381933952975 recsize=142 parentDocId=265429100712 
> firstip=91.203.187.6 hostHash32=0xb6cc6794 domHash32=0x306d52b9 
> siteHash32=0xb6cc6794 siteNumInlinks=0 addedTime=Mar 3 11:33:58 2015 
> UTC(1425382438) parentFirstIp=91.203.187.14 
> parentHostHash32=0xa6f718a4 parentDomHash32=0xdf624a2 
> parentSiteHash32=0xa6f718a4 hopCount=1 ufn=-1 priority=-1 ISNEWOUTLINK 
> PARENTHASADDRESS shardnum=88 
> url=http://static.v5.skyrock.net/css/common.css?en94Zsw 
> requestage=4753434s hadReply=0 errcount=1 errcode=32825(Doc is a dup)
>
> As you can see, GB indexes CSS files if they have a URL parameter. I 
> don't think it should.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gigablast/open-source-search-engine/issues/38>.
>

-- 
WARNING: CONFIDENTIALITY NOTICE: This E-mail and the materials attached are the private confidential property of the sender, and the message and attachments are privileged communications intended solely for the receipt, use, benefit, and information of the intended recipient indicated above. If you are not the intended recipient, you are hereby notified that any review, disclosure, copying, distribution, or the taking of any other action in reliance on the contents of this transmission is strictly prohibited, and may result in legal liability on your part. If you have received this transmission in error, please notify the sender immediately by replying to the sender, then fully delete the transmission from your computer and destroy any copies hereof. Your cooperation is appreciated.
