### ISSUE TITLE
Question : "Faceted" Search... regarding categorization of information

### ISSUE THREAD

**Issue by hwongcom** [gigablast/open-source-search-engine#39]
Is there a way I can categorize the information either through specifying in the crawler (/indexer) or search output is displayed with "categories or subcategories?"

e.g. if i searched for ... "Stalingrad", it'll be categorized under "Geography" etc.
e.g. also able to have some comparison with dmoz.org directory?

otherwise how can i confine the information to it's own search repository by specifying the links to crawl? 

i would like to have vertical niche search engine that.. when i specify category of "Business", it will only return business related websites... or  "Finance" or "Sports" etc... not within the search keywords but by faceting the categories...

How would you advise me going about doing this?

**Comment by gigablast** [comment]
gigablasts supports dmoz integration. just follow the instructions here:

http://www.gigablast.com/faq.html?c=main#dmoz
