### ISSUE TITLE
syllable division in PDF files

### ISSUE THREAD

**Issue by rpkZarathustra** [gigablast/open-source-search-engine#40]
Hello, 

indexing PDF files does not correct syllable division at the end of a line. 

For example:
"... by doing so, the author tells the reader a re-
markable story...."

This will be indexed as it is seen by the spider. Queries looking for "the reader a remarkable story" (e.g. without the syllable division) will fail. That phrase is simply not indexed. 

Is there any chance, that syllable division is ignored / undone by the spiders?

Thanks a lot, 

Zara

**Comment by gigablast** [comment]
it indexes word bigrams so hyphens should not pose an issue.
