### ISSUE TITLE
Parsing PDFs

### ISSUE THREAD

**Issue by rpkZarathustra** [gigablast/open-source-search-engine#41]
Hello again, 

It seems that certain PDFs are not parsed. For instance "http://othes.univie.ac.at/17009/1/2011-10-03_0002458.pdf" provides no content for the gigablast index.

Thanks, 

Zara

**Comment by rpkZarathustra** [comment]
Figured it out by myself. 

The file size was the problem. The source code in "XmlDoc.cpp" in line 53 says: "#define MAXDOCLEN (1024*1024)". This means that the maximum file size is 1 MB. I changed it to "#define MAXDOCLEN (1024*1024 * 20)" and compiled the code. Now this problem does not occur anymore.

Zara

**Comment by gigablast** [comment]
ill make a note of that on my end thanks!


On 07/03/2015 12:33 AM, rpkZarathustra wrote:
>
> Figured it out by myself.
>
> The file size was the problem. The source code in "XmlDoc.cpp" in line 
> 53 says: "#define MAXDOCLEN (1024/1024)". This means that the maximum 
> file size is 1 MB. I changed it to "#define MAXDOCLEN (1024/1024 * 
> 20)" and compiled the code. Now this problem does not occur anymore.
>
> Zara
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gigablast/open-source-search-engine/issues/41#issuecomment-118250479>.
>

-- 
WARNING: CONFIDENTIALITY NOTICE: This E-mail and the materials attached are the private confidential property of the sender, and the message and attachments are privileged communications intended solely for the receipt, use, benefit, and information of the intended recipient indicated above. If you are not the intended recipient, you are hereby notified that any review, disclosure, copying, distribution, or the taking of any other action in reliance on the contents of this transmission is strictly prohibited, and may result in legal liability on your part. If you have received this transmission in error, please notify the sender immediately by replying to the sender, then fully delete the transmission from your computer and destroy any copies hereof. Your cooperation is appreciated.
