### ISSUE TITLE
gigablast display search result 0

### ISSUE THREAD

**Issue by dipenpatel235** [gigablast/open-source-search-engine#42]
Hello....
i have set 3 server and 3 mirror server cluster.
now when i am search some words like "Mendipathar College" so it displayed result 0.
So what settings i need to change.
help me....

Thanks
Dipen Patel

**Comment by rpkZarathustra** [comment]
Did you sipder some pages including that phrase beforehand? Otherwise the search query cannot match since this phrase is not in the index.

**Comment by gigablast** [comment]
sounds like a good answer.
