### ISSUE TITLE
Cache and user administration

### ISSUE THREAD

**Issue by rpkZarathustra** [gigablast/open-source-search-engine#43]
Hi again, 

is there any chance to disable caching of parsed webpages? I think that this could save me a lot of disk space. 

My second question: Is there any user administration? As far as I can see everybody can query my version of Gigablast. Since it is accessable through the internet some hackers etc. could perform a DDoS attack oder something like that. A login and password needed to search via the API would be helpful... 

Thanks

**Comment by gigablast** [comment]
1. no, it needs them for summary generation etc.
2. there was some query password at one point, you can add it to 'master passwords' if you want to code it back in.
