### ISSUE TITLE
Merging search results from different collections

### ISSUE THREAD

**Issue by opguy** [gigablast/open-source-search-engine#45]
Again not an issue, just another query.

Does anyone know how to merge search results from different collections. I have created multiple collections to have better control over data, but I need to merge the search results from different collections.

Thanks

**Comment by gigablast** [comment]
look at the search api. you can do federated search across multiple collections: 

http://www.gigablast.com/api.html?c=main#/search

just use something like &c=mycoll1+mycoll2+...

**Comment by opguy** [comment]
Thanks, that was helpful.

Appreciate that.
