### ISSUE TITLE
Read/Edit data file

### ISSUE THREAD

**Issue by opguy** [gigablast/open-source-search-engine#47]
Again not an issue.

How can we read and edit data files. I am trying to find out way I can manipulate data in order to get rid of unwanted urls.

Thanks.

**Comment by gigablast** [comment]
click on 'tagdb'. you can enter in urls or sites into the text box and 
select 'manualban' and set the value to 1.  or you can ban entire sites 
from the search results page by clicking on the 'BAN' link if you are 
the admin.

On 07/18/2015 07:00 AM, opguy wrote:
>
> Again not an issue.
>
> How can we read and edit data files. I am trying to find out way I can 
> manipulate data in order to get rid of unwanted urls.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gigablast/open-source-search-engine/issues/47>.
>

-- 
WARNING: CONFIDENTIALITY NOTICE: This E-mail and the materials attached are the private confidential property of the sender, and the message and attachments are privileged communications intended solely for the receipt, use, benefit, and information of the intended recipient indicated above. If you are not the intended recipient, you are hereby notified that any review, disclosure, copying, distribution, or the taking of any other action in reliance on the contents of this transmission is strictly prohibited, and may result in legal liability on your part. If you have received this transmission in error, please notify the sender immediately by replying to the sender, then fully delete the transmission from your computer and destroy any copies hereof. Your cooperation is appreciated.

**Comment by opguy** [comment]
Thank, appreciate your response.

I am currently doing what you suggested, but thing is, I don't have idea of all the garbage sites my engine might have indexed. Until someone writes to me or I find out myself I am not sure what all  links I may have to remove. 

So, I was thinking if somehow I could see list of URLs index I might be able to remove the sites beforehand.

Thanks

**Comment by vonbetz** [comment]
If you want a dump of all of the urls in the index, use the gb dump command:

` ./gb dsh "./gb dump t main"|  sed -r -e 's/.*url=(.*)/\1/g'`

**Comment by opguy** [comment]
Thanks, that's helpful. Is there any way I can delete the urls directly?

Appreciate your response.

**Comment by gigablast** [comment]
just use the 'inject' tool and check the 'delete from index' box.


On 07/20/2015 09:44 PM, opguy wrote:
>
> Thanks, that's helpful. Is there any way I can delete the urls directly?
>
> Appreciate your response.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gigablast/open-source-search-engine/issues/47#issuecomment-123142569>.
>

-- 
WARNING: CONFIDENTIALITY NOTICE: This E-mail and the materials attached are the private confidential property of the sender, and the message and attachments are privileged communications intended solely for the receipt, use, benefit, and information of the intended recipient indicated above. If you are not the intended recipient, you are hereby notified that any review, disclosure, copying, distribution, or the taking of any other action in reliance on the contents of this transmission is strictly prohibited, and may result in legal liability on your part. If you have received this transmission in error, please notify the sender immediately by replying to the sender, then fully delete the transmission from your computer and destroy any copies hereof. Your cooperation is appreciated.

**Comment by opguy** [comment]
Thanks, that's what I am doing right now. Guess, that's the only way.

Thanks for your help.
