### ISSUE TITLE
GB shutting down very frequently after throwing segment fault

### ISSUE THREAD

**Issue by opguy** [gigablast/open-source-search-engine#48]
Hi,

Need urgent help. GB is shutting down very frequently after throwing segment fault. Could anyone help me figure out what's going on. Following is the error dump:

1438312553066 000 loop: sigbadhandler. disabling handler from recall.
1438312553066 000 gb: seg fault. printing stack trace. use 'addr2line -e gb' to decode the hex below.
1438312553085 000 addr2line -e gb 0x5537e6
1438312553085 000 addr2line -e gb 0x55452f
1438312553085 000 addr2line -e gb 0x6ef240
1438312553085 000 addr2line -e gb 0x551cd6
1438312553085 000 addr2line -e gb 0x496d04

**Comment by gigablast** [comment]
what is the output of
addr2line -e gb 0x6ef240


On 07/30/2015 09:20 PM, opguy wrote:
>
> Hi,
>
> Need urgent help. GB is shutting down very frequently after throwing 
> segment fault. Could anyone help me figure out what's going on. 
> Following is the error dump:
>
> 1438312553066 000 loop: sigbadhandler. disabling handler from recall.
> 1438312553066 000 gb: seg fault. printing stack trace. use 'addr2line 
> -e gb' to decode the hex below.
> 1438312553085 000 addr2line -e gb 0x5537e6
> 1438312553085 000 addr2line -e gb 0x55452f
> 1438312553085 000 addr2line -e gb 0x6ef240
> 1438312553085 000 addr2line -e gb 0x551cd6
> 1438312553085 000 addr2line -e gb 0x496d04
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gigablast/open-source-search-engine/issues/48>.
>

-- 
WARNING: CONFIDENTIALITY NOTICE: This E-mail and the materials attached are the private confidential property of the sender, and the message and attachments are privileged communications intended solely for the receipt, use, benefit, and information of the intended recipient indicated above. If you are not the intended recipient, you are hereby notified that any review, disclosure, copying, distribution, or the taking of any other action in reliance on the contents of this transmission is strictly prohibited, and may result in legal liability on your part. If you have received this transmission in error, please notify the sender immediately by replying to the sender, then fully delete the transmission from your computer and destroy any copies hereof. Your cooperation is appreciated.

**Comment by opguy** [comment]
sigaction.c:?

Earlier I had changed 'search control' settings and configured various parameter to '0' which started causing this issue. After I rolled back the changes this issue is not occurring (fingers crossed) anymore.
