### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by YPMEDIA** [gigablast/open-source-search-engine#51]
Hi, 

I have some questions concerning setup :

1. How to say to spider: "please only national website like *.de or *.co.uk" in site list ?
2. What is best practice to import aprox 2 million deep links ?
3. Proxy issue: I have set 4 nods and try to make proxy to collect results. But it doesn't work like described in hosts.conf.
Could somebody send me the working example ? 

My errors after start `./gb proxy load 0` 

`admin: need working-dir for host in hosts.conf line 121
db: hostdb init failed.
Failed to start gb. Exiting.`

if I make :

`proxy 6010 7010 8080 9010 46.4.442.222  /home-bildero/gigablast/data0/`

then get following error:

`admin: secondary host /home-bildero/gigablast/data0/   in hosts.conf not in /etc/hosts. Using secondary ethernet (eth1) ip of 46.4.442.222
gb: failed to ps auxww ntpd 2
db: ntpd not running on proxy
`

Thank you your help

Best 

Roman

**Comment by gigablast** [comment]
why are you trying to run the proxy? while it is in the code i wasn't planning on supporting that officially.

**Comment by YPMEDIA** [comment]
I have found information about proxy in hosts.conf :)

**Comment by lisawebcoder** [comment]
how do make added hosts run as a cluster?
i cant yet get it to work

Lisa
