### ISSUE TITLE
Feature Request: Approximate max. RAM Allocation Limit

### ISSUE THREAD

**Issue by martinvahi** [gigablast/open-source-search-engine#60]
It would be awesome to have people install their own private search engines at book shelves in the form of a [Raspberry Pi](https://www.raspberrypi.org/products/). People might have different Pi-s for different topic domains, different site collections and then just choose the link to the proper Pi from their company intranet HTML-page. By serving the search engine as a [Tor Hidden Service](https://www.torproject.org/docs/hidden-services.html.en), people can make their Pis available online even from home, from behind various fire-walls, link their home Pi to their Facebook page or Twitter tweats, at least for those, who use the [Tor Browser](https://www.torproject.org/projects/torbrowser.html.en) for browsing the web. That really opens up possibilities not just from privacy and security point of view, but from simple feature's point of view. It can take the content creation to a totally new level and not just for the politically minded, but also for  the "innocent and manipulatable".

Small companies might add the sites of their clients and potential clients to a custom instance of the Gigablast/Raspberry_Pi and if that one, single, Pi becomes too small, there's always the [Raspberry Pi clusters](https://www.youtube.com/watch?v=uNZ_EnwTg4Y), which can be increased as needed. The Pi is superior to an ordinary PC due to its smaller energy requirements, smaller electricity bills, specially for applications that are not in use most of the time, that just stand there and wait for the queries, not to mention the ability to invest to computing equipment gradually.

**Comment by Yeeler** [comment]
I have Odroid-U3, Cubie Board, Raspberry Pi 1 and 2. I run Odroid-U3 as a home server (email, web, ssh etc.) since it has much better hardware support than Raspberry Pi. I ran some GPIO experiments on the rest of them. As far as I am concerned, there single board computers are just toys. It costs less money and offer relatively better hardware. Efficiently, running Gigablast requires more CPUs and memories. Creating a big clusters, for instance, 40 Respberry Pis which would cost you more than USD 2000. I wouldn't suggest you do that unless you got lots of money. Moreover, network bandwidth is another consideration, for most of ISPs provide very low up-speed for normal home users, which means you can't run server at your home. Try this website, www.speedtest.net.  it will tell you how fast of your home internet. 

Eventually, Amazon EC2 might be a good choice, they claim that pay only what you use. Create some VMs on your PC first when you believe it is time to run GigaBlast on the Internet, move them to Amazon EC2.

**Comment by martinvahi** [comment]
Thank You for Your comment. I guess that if a server has about 10 end users maximum, who perform about 100 queries per day, then the upload speeds are probably not an issue. There might be an issue with latency, I haven't tested yet, but if I can watch comfortably any YouTube video in HihgDefinition with 10Mbps and have a symmetric connection that costs me in Tallinn about 15€, ~20$, per month and I'm actually using a slow version, if compared to other people, then I'm not really worried about upload speeds. I think that 2s per query on LAN can be acceptable. At least, if the software is properly designed, which the Gigablast probably IS, and the design has been updated to use the latest hardware, which it MIGHT NOT BE (I do not, yet, know), then it should be achievable. It is a fact that in year 2000 the PC-s were about the same as the old, version 1, Raspberry Pi-s are today. I guess that it boils down to the matter of tuning. 

What worries me a bit is that there are multiple pull requests pending. I really like the approach that software is not piled up  and the author takes his time before applying any modifications, because that keeps the project from turning into crapware, but it also seems to me that may be the project needs a bit modernization in terms of modularization. For example, the root folder of the project might be organized to sub-folders that reflect the functionality of the different components of the application. There is probably some code that is dedicated to storing and retrieving the document records from disk, there's probably some code that implements the spider that crawls and converts the raw data to the storable records, there is probably some code that implements the GUI, which might communicate with the retrieval part through a project specific, internal, API. The retrieval part probably contains some query transformation code that makes it possible to apply the queries to the set of records that have been stored. The store/retriaval part probably also contains some clearly distinguishable sub-component that handles the clustering and mirroring and so on and so forth. Right now it all seems to be one huge mix and new members of the open source project have to know everything rather than focus on some distinct component of the search engine. 

The requested approximate maximum RAM usage parametrization feature might be added after the restructuring of the existing code.

**Comment by Yeeler** [comment]
Exactly, if all the testing code gets peeled off from the GigaBlast project and put them into a sandbox to perform those testing. it will be awesome. I haven't got chance to go through all the source code.  More than 500k lines, I am scared,

**Comment by martinvahi** [comment]
A question: is there some console source code formatter that the developers of Gigablast have agreed upon?

The idea is that all of us have our preferences, but to keep the DIFF tool working a code should be formatted back to the "official style" before committing. I haven't done any C++ development lately, but I liked [Astyle](http://astyle.sourceforge.net/). The Astyle had various formatting parameters that were given as console arguments, so if Astyle is OK, then the way to format recursively on Linux might look like 

    find . -name '*.cpp' |xargs astyle the_arguments 
    find . -name '*.hpp' |xargs astyle the_arguments 
    find . -name '*.c'   |xargs astyle the_arguments 
    find . -name '*.h'   |xargs astyle the_arguments 

* The first task might be to agree on the formatter.

* The second task might be to write some sort of a [Travis CI](https://travis-ci.org/) tests for the fork. The tests do not need to do anything reasonable at first. The tests should just fail, if compilation fails. (it's free for open source projects on GitHub).

* The third task, milestone, might be to avoid making any changes to the engine and just try to divide the files to different folders so that the project at least compiles. Probably many files end up at a wrong folder at first, but that's just part of the process.

I'm willing to do it myself, but I do not want to fork the project in a development sense, because otherwise I would have to start merging other people's work manually to my fork and the fork would get abandoned. I propose that this repository here hosts the "stable", code and that the hacking takes place at [kalatestimine/open-source-search-engine](https://github.com/kalatestimine/open-source-search-engine), which is my, so to speak, "dirty" account that contains all sorts of temporary copies and is a general mess, not advertised for studying and is a kind of account that I do not want search engines to associate with my name. The user ["kalatestimine"](https://github.com/kalatestimine) is actually me. The word "kala" stands for "fish" in Estonia and is an Estonian analogue for "bug" in the context of software flaws, because fishes are slippery and an Estonian expression "viga lipsas sisse" translates as "a mistake slipped in". In Estonian slang "buggy" is "kalane", which has a direct translation of "fishy". The word "testimine" translates as "test-ing". So "kalatestimine" has a approximate, non-official, slang, meaning of "bug-testing".

What regards to a C++ IDE, then I thing everyone has its own choice and everyone should have the opportunity to use, what ever he/she likes. I would not touch the build system, except that it is a fact of life that different operating systems have different build systems. I've heard of the Ant/Maven/Gardle/[Boost_build](http://www.boost.org/build/)/[CMake](https://cmake.org/)/etc. but clearly the world is more complex than that. Therefore, I see that the current Makefile should be the "reference implementation" that documents the build process and then there should be a separate folder with sub folders for all the rest of the build systems and their scripts. I propose the following folder structure:

    the_project_main_after_download
      |
      +--README.md   (the project main README, introducing the project and its folder structure)
      |
      +--doc
      |   |
      |   +--Doxygen (a folder autogenerated by a doc. build script)
      |   |
      |   +--marketing_materials (an optional folder for artwork development files, logos, etc.)
      |
      +--src 
          |
          +--devel_tools    (all build scripts, selftests, doc. building scripts)
          |   |
          |   +--README.md (an intro to this folder)
          |   |
          |   +--build_systems
          |   |   |
          |   |   +--README.md (an intro to this folder)
          |   |   |
          |   |   +--reference_build_system 
          |   |   |   |
          |   |   |   +--Makefile (the current Makefile)
          |   |   |
          |   |   +--Visual_Studio (and whatever else anybody wants to add
          |   |   |
          |   |   +--doxygen_build_system_t1 (t1 stands for "type 1", hinting that 
          |   |                               different people might want to 
          |   |                               use different source tree copy preprocessing 
          |   |                               for generating the doxygen documentation.)
          |   |                       
          |   +--tests
          |       |
          |       +--README.md (an intro to this folder)
          |       |
          |       +--Travis_CI
          |       |
          |       +--selftests (the collection of tests for testing 
          |                     separate components, internal 
          |                     libraries of the Gigablast)
          |
          +--devel  (a clean copy of the engine source, the thing that is being built)
          |
          +--deployment_deliverables (automatically generated, 
          |                          contains build results, regardless of
          |                          whether it was an instrumented
          |                          debug build or the actual deployment binary.
          |                          It is safe to delete this folder any time,
          |                          except, when the program is running.
          |                          At first the build scripts may just rsync 
          |                          the content of devel to this folder before build.)
          |
          +--third_party (Dependencies that are
          |              not developed by this project. By keeping
          |              third party components outside of devel, the
          |              devel can be grepped recursively without
          |              running into the dependencies.
          |              Project settings at IDE-s can be set to
          |              ignore this folder, allowing the IDE to
          |              save substantial amount of computing resources.)
          |
          |
          +--search_engine_data_store (autogenerated by
                                      the search engine)

Thank You for reading this comment. What do You thing?

**Comment by gigablast** [comment]
the max ram parameter is now back in the master branch. it was taken out a while ago for simplicity, but it seems to be too essential to omit.  

as far as the other various topics on this thread
1) we're a search engine, not a directory, so hiearchial directories are not relevant here. ;)
2) code formatting is not important at this point. there are other more pending issues. can you use an IDE that does it transparently?

**Comment by martinvahi** [comment]
Could You please offer instructions, how to use the max RAM parameter, where to set it, etc.?

By recursive grepping 2015_11 version of the src I found that the word "RAM" and "ram" were mentioned at a few places, but I was not able to classify those regions as the setup region for the max. RAM parameter.

**Comment by gigablast** [comment]
there is a max memory parameter in the master controls. or you can set it directly in the gb.conf before starting gb.

**Comment by martinvahi** [comment]
I'm not sure that it is working. In a VirtualBox appliance on a 64b CPU the situation looks like that:

    gigablast_runner[gb]$ free
                 total       used       free     shared    buffers     cached
    Mem:       1771792     775380     996412          0          0     545060
    -/+ buffers/cache:     230320    1541472
    Swap:      1028156     119052     909104
    gigablast_runner[gb]$ ./gb
    db: Logging to file /dev/stderr.
    db: Use 'gb -d' to run as daemon. Example: gb -d
    1449179176020 000 conf: Gigablast Version: Dec  3 2015 23:06:45
    1449179176021 000 conf: Gigablast Architecture: 64-bit 
    1449179176021 000 host: Working directory is
    /home/gigablast_runner/gigablast/gb/
    1449179176021 000 host: Using /home/gigablast_runner/gigablast/gb/hosts.conf
    1449179176021 000 host: Process ID is 1294
    1449179176021 000 host: Detected local ip 127.0.0.1
    1449179176021 000 host: Detected local ip 192.168.0.106
    1449179176021 000 host: Running as host id #0
    1449179176348 000 wikt: Loading
    /home/gigablast_runner/gigablast/gb/wiktionary-syns.dat
    1449179176506 000 wikt: Loading
    /home/gigablast_runner/gigablast/gb/wiktionary-buf.txt
    1449179176607 000 wikt: test "love" -> "en|love,loved,loving,loves"
    1449179176608 000 wiki: Loading
    /home/gigablast_runner/gigablast/gb/wikititles2.dat
    1449179176608 000 mem: addMem(100663296): tbl-wiki. ptr=0x7ffd2eb56014
    used=127113172
    
    1449179176736 000 mem: malloc(349869920): Out of memory
    1449179176737 000 db: Posdb init failed.
    Failed to start gb. Exiting.
    gigablast_runner[gb]$ vim ./gb.conf
    gigablast_runner[gb]$ ./gb
    db: Logging to file /dev/stderr.
    db: Use 'gb -d' to run as daemon. Example: gb -d
    1449179206018 000 conf: Gigablast Version: Dec  3 2015 23:06:45
    1449179206018 000 conf: Gigablast Architecture: 64-bit 
    1449179206018 000 host: Working directory is
    /home/gigablast_runner/gigablast/gb/
    1449179206018 000 host: Using /home/gigablast_runner/gigablast/gb/hosts.conf
    1449179206018 000 host: Process ID is 1313
    1449179206018 000 host: Detected local ip 127.0.0.1
    1449179206018 000 host: Detected local ip 192.168.0.106
    1449179206018 000 host: Running as host id #0
    1449179206326 000 wikt: Loading
    /home/gigablast_runner/gigablast/gb/wiktionary-syns.dat
    
    1449179206494 000 wikt: test "love" -> "en|love,loved,loving,loves"
    1449179206494 000 wiki: Loading
    /home/gigablast_runner/gigablast/gb/wikititles2.dat
    1449179206494 000 mem: addMem(100663296): tbl-wiki. ptr=0x7f58c3673014
    used=127113172
    1449179206616 000 db: Loading conf for collection main (0)
    1449179206623 000 mem: addMem(349869920): buckets-posdb. ptr=0x7f58adf02014
    used=238787108
    1449179206624 000 mem: malloc(193164080): Out of memory
    1449179206624 000 RdbMem::init: Cannot allocate memory
    1449179206624 000 db: Failed to initialize memory: Cannot allocate memory.
    1449179206624 000 db: Titledb init failed.
    Failed to start gb. Exiting.
    1449179206626 000 db: Resetting tree for titledb.
    1449179206626 000 loop: sigbadhandler. disabling handler from recall.
    1449179206626 000 gb: seg fault. printing stack trace. use 'addr2line -e gb'
    to decode the hex below.
    1449179206652 000 addr2line -e gb 0x5836e1
    1449179206652 000 addr2line -e gb 0x7f58e0a57670
    1449179206652 000 addr2line -e gb 0x5212ab
    1449179206652 000 addr2line -e gb 0x520d1f
    1449179206652 000 addr2line -e gb 0x5208ce
    1449179206652 000 addr2line -e gb 0x4feafe
    1449179206652 000 addr2line -e gb 0x7f58df854669
    1449179206652 000 addr2line -e gb 0x7f58df8546b5
    1449179206652 000 addr2line -e gb 0x7f58df83bd8c
    1449179206652 000 addr2line -e gb 0x4056b9
    1449179206652 000 loop: sigbadhandler. trying to save now. mode=0
    1449179206652 000 mem: checking mem for breeches
    1449179206726 000 gb: Shutting down urgently. Timed try #0.
    1449179206726 000 gb: disabling threads
    Segmentation fault (core dumped)
    gigablast_runner[gb]$ ./gb
    db: Logging to file /dev/stderr.
    db: Use 'gb -d' to run as daemon. Example: gb -d
    1449179216494 000 conf: Gigablast Version: Dec  3 2015 23:06:45
    1449179216494 000 conf: Gigablast Architecture: 64-bit 
    1449179216494 000 host: Working directory is
    /home/gigablast_runner/gigablast/gb/
    1449179216494 000 host: Using /home/gigablast_runner/gigablast/gb/hosts.conf
    1449179216494 000 host: Process ID is 1316
    1449179216495 000 host: Detected local ip 127.0.0.1
    1449179216495 000 host: Detected local ip 192.168.0.106
    1449179216495 000 host: Running as host id #0
    1449179216930 000 wikt: Loading
    /home/gigablast_runner/gigablast/gb/wiktionary-syns.dat
    1449179217050 000 wikt: Loading
    /home/gigablast_runner/gigablast/gb/wiktionary-buf.txt
    1449179217087 000 wikt: test "love" -> "en|love,loved,loving,loves"
    1449179217088 000 wiki: Loading
    /home/gigablast_runner/gigablast/gb/wikititles2.dat
    1449179217088 000 mem: addMem(100663296): tbl-wiki. ptr=0x7f8981ad2014
    used=127113172
    1449179217204 000 db: Loading conf for collection main (0)
    1449179217211 000 mem: addMem(349869920): buckets-posdb. ptr=0x7f896c361014
    used=238787108
    1449179217212 000 mem: malloc(193164080): Out of memory
    1449179217212 000 RdbMem::init: Cannot allocate memory
    1449179217212 000 db: Failed to initialize memory: Cannot allocate memory.
    1449179217212 000 db: Titledb init failed.
    Failed to start gb. Exiting.
    1449179217213 000 db: Resetting tree for titledb.
    1449179217213 000 loop: sigbadhandler. disabling handler from recall.
    1449179217213 000 gb: seg fault. printing stack trace. use 'addr2line -e gb'
    to decode the hex below.
    1449179217214 000 addr2line -e gb 0x5836e1
    1449179217214 000 addr2line -e gb 0x7f899eeb6670
    1449179217214 000 addr2line -e gb 0x5212ab
    1449179217214 000 addr2line -e gb 0x520d1f
    1449179217214 000 addr2line -e gb 0x5208ce
    1449179217214 000 addr2line -e gb 0x4feafe
    1449179217214 000 addr2line -e gb 0x7f899dcb3669
    1449179217225 000 addr2line -e gb 0x7f899dcb36b5
    1449179217226 000 addr2line -e gb 0x7f899dc9ad8c
    1449179217226 000 addr2line -e gb 0x4056b9
    1449179217226 000 loop: sigbadhandler. trying to save now. mode=0
    1449179217226 000 mem: checking mem for breeches
    1449179217286 000 gb: Shutting down urgently. Timed try #0.
    1449179217286 000 gb: disabling threads
    Segmentation fault (core dumped)
    gigablast_runner[gb]$ free
                 total       used       free     shared    buffers     cached
    Mem:       1771792    1065832     705960          0          0     819532
    -/+ buffers/cache:     246300    1525492
    Swap:      1028156     118328     909828
    gigablast_runner[gb]$ uname -a
    Linux darkstar 3.10.17 #2 SMP Fri Feb 14 16:45:28 CST 2014 x86_64 AMD
    Athlon(tm) II X2 255 Processor AuthenticAMD GNU/Linux
    gigablast_runner[gb]$ date
    Thu Dec  3 23:48:18 EET 2015
    gigablast_runner[_tmp]$ gcc -v
    Reading specs from /usr/lib64/gcc/x86_64-slackware-linux/4.8.2/specs
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-slackware-linux/4.8.2/lto-wrapper
    Target: x86_64-slackware-linux
    Configured with: ../gcc-4.8.2/configure --prefix=/usr --libdir=/usr/lib64 --mandir=/usr/man --infodir=/usr/info --enable-shared --enable-bootstrap --enable-languages=ada,c,c++,fortran,go,java,lto,objc --enable-threads=posix --enable-checking=release --enable-objc-gc --with-system-zlib --with-python-dir=/lib64/python2.7/site-packages --disable-libunwind-exceptions --enable-__cxa_atexit --enable-libssp --enable-lto --with-gnu-ld --verbose --enable-java-home --with-java-home=/usr/lib64/jvm/jre --with-jvm-root-dir=/usr/lib64/jvm --with-jvm-jar-dir=/usr/lib64/jvm/jvm-exports --with-arch-directory=amd64 --with-antlr-jar=/tmp/gcc/antlr-runtime-3.4.jar --enable-java-awt=gtk --disable-gtktest --disable-multilib --target=x86_64-slackware-linux --build=x86_64-slackware-linux --host=x86_64-slackware-linux
    Thread model: posix
    gcc version 4.8.2 (GCC) 
    gigablast_runner[_tmp]$ which gcc
    /usr/bin/gcc
    gigablast_runner[_tmp]$ 

It was compiled with GCC and with a modification that all "-O2" in the Makefile were replaced with "-O3" and 

    -m64 -ftree-vectorize 

were added to the branch that was used in this instance.

The situation was not much better after downloading the 2015_12_05 version of the the Gigablast and recompiling it without any modifications:
    
    1449181496007 000 gb: calling save tree for rdbid 0
    1449181496008 000 gb: calling save tree for rdbid 0
    1449181496008 000 gb: Shutting down udp server port 5998.
    1449181496008 000 gb: Closing udp server socket port 5998.
    1449181496008 000 gb: Shut down udp server port 5998 successfully.
    1449181496008 000 gb: Shutting down udp server port 9000.
    1449181496008 000 gb: Closing udp server socket port 9000.
    1449181496008 000 gb: Shut down udp server port 9000 successfully.
    1449181496008 000 admin: stopping real time profiler
    1449181496008 000 gb: Saving miscellaneous data files.
    1449181496009 000 admin: Error writing to /home/gigablast_runner/gigablast/gb/gb.conf: Cannot allocate memory
    1449181496009 000 admin: Error writing to /home/gigablast_runner/gigablast/gb/coll.main.0/coll.conf: Cannot allocate memory
    1449181496010 000 build: Saving /home/gigablast_runner/gigablast/gb/addsinprogress.saving
    1449181496010 000 db: Saving 128000 bytes of cache to /home/gigablast_runner/gigablast/gb//dns.cache
    1449181496012 000 gb: Dumping core after saving.
    Aborted (core dumped)
    gigablast_runner[gb]$ free
                 total       used       free     shared    buffers     cached
    Mem:       1771792     588620    1183172          0          0     263592
    -/+ buffers/cache:     325028    1446764
    Swap:      1028156     264100     764056
    gigablast_runner[gb]$

[2015_12_05_Gigablast_Default_Version_in_VirtualBox_appliance.txt](https://github.com/gigablast/open-source-search-engine/files/51437/2015_12_05_Gigablast_Default_Version_in_VirtualBox_appliance.txt)


[2015_12_05_gigablast_bug_report_by_martin_vahi_conf_files.zip](https://github.com/gigablast/open-source-search-engine/files/51426/2015_12_05_gigablast_bug_report_by_martin_vahi_conf_files.zip)

**Comment by martinvahi** [comment]
My current comment is not related to any flaws. It is an announcement that I [published](http://technology.softf1.com/mmmv_raspbian_t1/mmmv_gigablast_container_t1/) an AMD64  VirtualBox appliance that contains a Gigablast instance that can be started by just running a start-up script. The Gigablast instance is in a state, where the end user has to set the Gigablast administrator password and give a list of sites to be crawled.
