### ISSUE TITLE
Dependence on GCC Extension that is not Supported by Clang

### ISSUE THREAD

**Issue by martinvahi** [gigablast/open-source-search-engine#69]
An excerpt from console:

    XmlDoc.cpp:46419:17: error: variable length array of non-POD element type 'SafeBuf'
            SafeBuf hostBin[g_hostdb.m_numHosts];
                           ^
    XmlDoc.cpp:50874:12: warning: 'this' pointer cannot be null in well-defined C++ code; pointer may be assumed to
          always convert to true [-Wundefined-bool-conversion]
                                                  this, // xd holder (Msg25::m_xd)
                                                  ^~~~
    7 warnings and 1 error generated.
    Makefile:603: recipe for target 'XmlDoc.o' failed
    make: *** [XmlDoc.o] Error 

A citation from [LLVM home page](http://clang.llvm.org/compatibility.html#vla):

# Variable-length arrays 

GCC and C99 allow an array's size to be determined at run time. This extension is not permitted in standard C++. However, Clang supports such variable length arrays in very limited circumstances for compatibility with GNU C and C99 programs:

* The element type of a variable length array must be a POD ("plain old data") type, which means that it cannot have any user-declared constructors or destructors, any base classes, or any members of non-POD type. All C types are POD types.

* Variable length arrays cannot be used as the type of a non-type template parameter.

If your code uses variable length arrays in a manner that Clang doesn't support, there are several ways to fix your code:

- replace the variable length array with a fixed-size array if you can determine a reasonable upper bound at compile time; sometimes this is as simple as changing int size = ...; to const int size = ...; (if the initializer is a compile-time constant);
- use std::vector or some other suitable container type; or
- allocate the array on the heap instead using new Type[] - just remember to delete[] it.

**Comment by martinvahi** [comment]
I have not studied the code, but at first glance I might study the suitability of a solution, where the **std::vector** instance is allocated with the dynamically determined size and then the pointer to the **instance[0]** is used in the role of the variable **hostBin**. That would delegate the memory management to the std::vector but allow to avoid the index operator function calls by operating directly on the plain array that the std::vector instance wraps.

The question is, shall I even bother offering a pull requests or is my approach too extreme to be merged? I do not want to spend my time working on the changes, when the changes are unacceptable.

**Comment by Gyscos** [comment]
Index operator in `std::vector` are inlined and not bound-checked anyway - any reason not to use it?
I'd guess the bigger difference is that it would be allocated on the heap, rather than on the stack.
You'd probably need to benchmark to see if the difference is noticeable.

**Comment by gigablast** [comment]
both of these issues are fixed in the 'testing' branch.
