### ISSUE TITLE
Inconsistency in Gigablast Web Search Appliance Advertisement

### ISSUE THREAD

**Issue by martinvahi** [gigablast/open-source-search-engine#74]
Citations from 2016_02_20 [archival copy](https://archive.is/ZPkbc) of  

[https://www.gigablast.com/appliance.html](https://www.gigablast.com/appliance.html)

> Up to 200 can be networked together to achieve an index over 100 billion pages.

> Over 200 appliances can be networked together to search over 100 billion web pages;

**Comment by martinvahi** [comment]
A non-related side-question is that is the development of the open source version abandoned? A quote:

> Beefed Up. In addition to many reliability enhancements and new features, the commercial version of Gigablast, Gigablast PRO™, serves signficantly higher quality results at incredibly faster speeds when compared to the freely available open source solution.

**Comment by gigablast** [comment]
i don't see the inconsistency. basically 200 appliances can seach 100B web pages.

but, no, it's not abandoned. the open source version is still getting updates. you can see the updates coming in on a regular basis.

**Comment by martinvahi** [comment]
"Up to 200 whatever" and "Over 200 whatever" look more like different ranges to me. 

    Up to 200:  [0   ,200]
    Over 200:   [200, 200+c] where 0<c

That's where I saw the inconsistency.

I'm glad that the open source version is not abandoned, but I'm also curious, how the Pro version can be any better than the open source version, unless it contains some closed source library that can not be part of the open source version due to licensing issues? Could You please offer some hints?

Thank You. :-)
