### ISSUE TITLE
Rebalance does not work as expected

### ISSUE THREAD

**Issue by br-privacore** [gigablast/open-source-search-engine#75]
We have a production system with 140 shards, and I'm setting up a test system with 4 shards. I want to run a test with 4 shards (1 host each) having half as much data as the production system's shards.

I copied data from production to test:
Production host 0 -> test host 0
Production host 1 -> test host 1

I added the two hosts to hosts.conf, deleted rebalance.txt on both hosts and started the system up. Worked fine, no rebalance required.

I shut down the two hosts, and added host 2 and 3 (which have no data) to the hosts.conf files for all 4 hosts. 

hosts.conf:
0 25998 27000 28000 29000 192.168.4.10 192.168.4.10 /mnt/data_raid1_07/spare1/test_4_instances_setup2/000/ nospider
1 25997 27001 28001 29001 192.168.4.10 192.168.4.10 /mnt/data_raid1_07/spare1/test_4_instances_setup2/001/ nospider
2 25996 27002 28002 29002 192.168.4.10 192.168.4.10 /mnt/data_raid1_07/spare1/test_4_instances_setup2/002/ nospider
3 25995 27003 28003 29003 192.168.4.10 192.168.4.10 /mnt/data_raid1_07/spare1/test_4_instances_setup2/003/ nospider

Started the system, and got the message "A host requires a shard rebalance. Click 'rebalance shards' in the master controls to rebalance all hosts." as expected.

I started the rebalance, expecting the data from host 0 and 1 to be distributed evenly between all 4 hosts. That did not happen - no data was moved.

**Comment by br-privacore** [comment]
Thinking about it, it of course boils down to the way data is distributed in gb. It uses a map, hostdb.m_map, with 8192 slots, which it assigns host ids sequentially. So in the scenario with 4 hosts, they would be 0,1,2,3,0,1,2,3,0,1,2,3 etc. As I took the data from host 0, the hashes of the keys stored there would all hit a slot pointing to host 0, also when using 4 hosts instead of 140. 

So probably a non-issue if doing a full rebalance with all data.

**Comment by dp40oz** [comment]
Would you be able to elaborate on this? I was running 1 shard then I expanded to 4. The first shard though still has all the info it had before. So it's using much more disk space than the other 3. Any clarification on why this is and how I can rectify it would be great. Thanks.

**Comment by gigablast** [comment]
you have to click the 'rebalance shards' link in the 'master controls'. then host #0 will copy some data over to the 3 new hosts.
