### ISSUE TITLE
Parms.cpp: local variable 't' not initialized

### ISSUE THREAD

**Issue by isj-privacore** [gigablast/open-source-search-engine#76]
In saveToXml(): if m_size is non-zero the initialization of 't' is bypassed which can lead to options not being saved, depending on which value happens to be on the stack. Found with FlexeLint.

Solved in our fork, commit 20a967f12855bf39c7d4ff692bdf1a518a81dc3d: https://github.com/privacore/open-source-search-engine/commit/20a967f12855bf39c7d4ff692bdf1a518a81dc3d

**Comment by gigablast** [comment]
thanks, incorporated.
