### ISSUE TITLE
Title::setTitle() buffer overscan

### ISSUE THREAD

**Issue by isj-privacore** [gigablast/open-source-search-engine#77]
Title::setTitle() scans beyond the end of the rootTitleBuf.
There is usually a ascii-nul after the end but not always.

Solved in our fork, commit 9dbc12953b7bbf465fc9a680bf614dab81718b94: https://github.com/privacore/open-source-search-engine/commit/628744f25a8fb0f9624c5f8b43a67162f25f346b

**Comment by gigablast** [comment]
thanks, incorporated.
