### ISSUE TITLE
Test for iconv_open() failure correctly

### ISSUE THREAD

**Issue by isj-privacore** [gigablast/open-source-search-engine#78]
In Unicode.cpp:
  if ( cd_latin1_u8 < 0) {
iconv_t is a pointer and cannot be begative. GCC optimizes out of it and the error check effectively doesn't work.

Solved in our fork, commit https://github.com/privacore/open-source-search-engine/commit/c8b5771956fafcd60c2173c2334eaa60394bdffb

**Comment by gigablast** [comment]
thanks, incorporated.
