### ISSUE TITLE
Synonyms::addStripped() incorrectly assumes ascii-nul termination

### ISSUE THREAD

**Issue by isj-privacore** [gigablast/open-source-search-engine#79]
Synonyms::addStripped() assumes that stripAccentMarks() outputs a NUL-terminated string, which it doesn't, leading to SafeBuf::safeStrcpy() scanning beyond buffer end.

Solved in our fork, commit https://github.com/privacore/open-source-search-engine/commit/f3153425a7807e26e5f2eae58e800620be6248eb

**Comment by gigablast** [comment]
thanks, incorporated.
