### ISSUE TITLE
Mime headers parsed from connection refused 

### ISSUE THREAD

**Issue by isj-privacore** [gigablast/open-source-search-engine#80]
If connection is refused when fetching robots.txt then GB tries to parse the non-existing MIME headers, leading to use of undefined memory.

Solved in our fork, commit https://github.com/privacore/open-source-search-engine/commit/cda9c7c0edf74ab7fd6f344b1c850354d97d67fa

**Comment by gigablast** [comment]
thanks, incorporated.
