### ISSUE TITLE
Read-below-stack in Msg20Reply::serialize()

### ISSUE THREAD

**Issue by isj-privacore** [gigablast/open-source-search-engine#84]
XmlDoc::getMsg20Reply() is using local stack buffers and setting pointer members in Msg20Reply to point them and then returning. Valgrind found that below-stack-memory is referenced in Msg20Reply::serialize()

Solved in our fork: https://github.com/privacore/open-source-search-engine/commit/b18e363e3e9788fb8eafdaed575b0ce83382b0d3

**Comment by gigablast** [comment]
thanks! fixed in diffbot-testing branch, will be merged into master soon.
