### ISSUE TITLE
"add URL" for non-zero collections

### ISSUE THREAD

**Issue by isj-privacore** [gigablast/open-source-search-engine#85]
The "Add URL" function doesn't parse the 'c' parameter so the InjectionRequest.m_collnum is always zero. This bug shows up when using a non-initial collection.

Solved in our fork: https://github.com/privacore/open-source-search-engine/commit/0b2e2bbe3db50d34a36b171835a87e43292906bd

**Comment by gigablast** [comment]
thanks, incorporating into master!
