### ISSUE TITLE
Url::getDisplayUrl does not handle xn-- in url path correctly

### ISSUE THREAD

**Issue by alc-privacore** [gigablast/open-source-search-engine#88]
Url::getDisplayUrl does not handle xn-- in url path correctly when url is a normal (non-idn) domain.

eg:
www.gandi.net/domain/xn--q9jyb4c/info
gets converted to
www.gandi.net/domain/http://www.gandi.net/domain/xn--q9jyb4c/info

Solved in our fork, commit privacore@a1df6baa1d89e70261afcf1c3d2ab076e31a827a

**Comment by gigablast** [comment]
thanks again. these are in diffbot-testing and will be in master soon. :)

**Comment by santamonicajoe** [comment]
Unsubscribe
